/**
 * C3 Runtime Bridge — injectable script for Construct 3 projects.
 *
 * This module generates a JavaScript file that, when added to a C3 project's
 * script files, exposes the C3 runtime via a command queue on globalThis.
 * External tools (Playwright, browser console, desktop automation, etc.) can
 * then submit commands to control the game and read state.
 *
 * The bridge runs INSIDE the browser alongside the C3 game. It:
 * 1. Captures the IRuntime reference via runOnStartup()
 * 2. Starts a fetch-polling endpoint (no WebSocket needed)
 * 3. Exposes: callFunction, getGlobalVar, setGlobalVar, getObjectInstance,
 *    evaluateExpression, getLayout, subscribeEvent
 *
 * Why fetch-polling instead of WebSocket:
 * - No additional server needed on the host machine
 * - Works via browser console or any CDP-capable automation tool
 * - Simpler to implement, debug, and doesn't require extra ports
 *
 * Architecture:
 *   Host machine
 *   ├── Browser with C3 game loaded
 *   │   └── runtime-bridge.js (this script)
 *   │       └── window.__c3bridge = { command queue + result store }
 *   └── curl / python / Playwright reads __c3bridge via CDP or DOM injection
 */

/**
 * Returns the JavaScript source code for the runtime bridge script.
 * This gets written to a .js file inside the C3 project's scripts/ folder.
 */
export function generateBridgeScript(): string {
  return `// C3 Runtime Bridge — auto-generated by construct3-mcp
// Exposes the C3 runtime for external automation and testing.
// Do NOT edit manually; regenerate with inject_runtime_bridge tool.

runOnStartup(async (runtime) => {
  // Store runtime globally for external access
  globalThis.__c3Runtime = runtime;

  // Command/response bridge for structured communication
  const bridge = {
    // Pending commands from external tools
    _queue: [],
    // Results keyed by command ID
    _results: {},
    // Auto-incrementing command ID
    _nextId: 1,

    // External tools call this to submit a command
    submit(type, args) {
      const id = this._nextId++;
      this._queue.push({ id, type, args });
      return id;
    },

    // External tools poll this to get results
    getResult(id) {
      const r = this._results[id];
      if (r) delete this._results[id]; // consume once
      return r ?? null;
    },

    // Current runtime state snapshot
    getState() {
      return {
        ready: true,
        layoutName: runtime.layout?.name ?? null,
        tickCount: runtime.tickCount,
        gameTime: runtime.gameTime,
        dt: runtime.dt,
        objectCount: runtime.objects ? Object.keys(runtime.objects).length : 0,
      };
    },
  };

  globalThis.__c3bridge = bridge;

  // Process command queue each tick
  runtime.addEventListener("tick", () => {
    while (bridge._queue.length > 0) {
      const cmd = bridge._queue.shift();
      try {
        let result;
        switch (cmd.type) {
          case "callFunction":
            result = runtime.callFunction(cmd.args.name, ...( cmd.args.params ?? []));
            break;

          case "getGlobalVar":
            result = runtime.globalVars[cmd.args.name];
            break;

          case "setGlobalVar":
            runtime.globalVars[cmd.args.name] = cmd.args.value;
            result = { set: true, name: cmd.args.name, value: cmd.args.value };
            break;

          case "getObjectState": {
            const objType = runtime.objects[cmd.args.objectName];
            if (!objType) {
              result = { error: "Object not found: " + cmd.args.objectName };
              break;
            }
            const inst = objType.getFirstInstance();
            if (!inst) {
              result = { error: "No instances of: " + cmd.args.objectName };
              break;
            }
            // Read requested properties or return defaults
            const props = cmd.args.properties ?? ["x", "y", "width", "height", "isVisible", "opacity"];
            const state = {};
            for (const p of props) {
              try { state[p] = inst[p]; } catch { state[p] = undefined; }
            }
            // Include instance variables
            if (inst.instVars) {
              state._instVars = {};
              for (const [k, v] of Object.entries(inst.instVars)) {
                state._instVars[k] = v;
              }
            }
            // Include behaviors
            if (inst.behaviors) {
              state._behaviors = {};
              for (const [k, v] of Object.entries(inst.behaviors)) {
                try { state._behaviors[k] = { exists: true }; } catch { /* skip */ }
              }
            }
            result = state;
            break;
          }

          case "getAllInstances": {
            const ot = runtime.objects[cmd.args.objectName];
            if (!ot) {
              result = { error: "Object not found: " + cmd.args.objectName };
              break;
            }
            const insts = ot.getAllInstances();
            result = {
              count: insts.length,
              instances: insts.slice(0, cmd.args.limit ?? 50).map((inst, i) => ({
                index: i,
                uid: inst.uid,
                x: inst.x, y: inst.y,
                isVisible: inst.isVisible,
              })),
            };
            break;
          }

          case "getLayout":
            result = {
              name: runtime.layout.name,
              width: runtime.layout.width,
              height: runtime.layout.height,
              layers: runtime.layout.getAllLayers().map(l => ({
                name: l.name,
                isVisible: l.isVisible,
                opacity: l.opacity,
                index: l.index,
              })),
            };
            break;

          case "goToLayout":
            runtime.goToLayout(cmd.args.name);
            result = { navigated: cmd.args.name };
            break;

          case "evaluateExpression": {
            // Evaluate a plugin expression by accessing an object's properties
            const obj = runtime.objects[cmd.args.objectName];
            if (!obj) {
              result = { error: "Object not found: " + cmd.args.objectName };
              break;
            }
            const instance = obj.getFirstInstance();
            if (!instance) {
              result = { error: "No instances of: " + cmd.args.objectName };
              break;
            }
            try {
              result = instance[cmd.args.expression];
            } catch (e) {
              result = { error: String(e) };
            }
            break;
          }

          case "listObjects":
            result = Object.keys(runtime.objects);
            break;

          case "listGlobalVars":
            result = Object.entries(runtime.globalVars).reduce((acc, [k, v]) => {
              acc[k] = v;
              return acc;
            }, {});
            break;

          case "ping":
            result = { pong: true, time: Date.now() };
            break;

          default:
            result = { error: "Unknown command: " + cmd.type };
        }
        bridge._results[cmd.id] = { ok: true, value: result };
      } catch (e) {
        bridge._results[cmd.id] = { ok: false, error: String(e) };
      }
    }
  });

  console.log("[c3-bridge] Runtime bridge initialized. Access via globalThis.__c3bridge");
});
`;
}

/**
 * Returns the path where the bridge script should be written
 * relative to the C3 project root.
 */
export function getBridgeScriptPath(): string {
  return 'scripts/c3-runtime-bridge.js';
}

/**
 * Returns the entry that needs to be added to the project's
 * script files list in project.c3proj.
 */
export function getBridgeProjectEntry(): { name: string; type: string; purpose: string } {
  return {
    name: 'c3-runtime-bridge.js',
    type: 'script',
    purpose: 'none', // auto-runs via runOnStartup
  };
}
