/**
 * C3 Runtime Bridge: an injectable script for Construct 3 projects.
 *
 * This module generates a JavaScript file that, added to a project's script
 * files, exposes the runtime through a command queue on globalThis. The MCP
 * tools reach it over the Chrome DevTools Protocol (connect_to_game and
 * call_bridge submit a command and poll for its result); a browser console
 * or any CDP-capable tool can do the same.
 *
 * The bridge runs inside the browser alongside the game. It:
 * 1. Captures the IRuntime reference via runOnStartup()
 * 2. Keeps a command queue and a result store on globalThis.__c3bridge
 * 3. Processes queued commands on every documented runtime tick
 * 4. Keeps event subscriptions (global-variable changes, layout changes and
 *    explicit custom events) in bounded per-subscription buffers, filled
 *    from documented runtime state each tick
 *
 * Only documented scripting interfaces are used: IRuntime.globalVars,
 * IRuntime.layout, tickCount and the tick event. There is no documented
 * observer of every event-sheet signal or plugin trigger, so a generic
 * "signal" subscription is not offered.
 */

/**
 * Returns the JavaScript source code for the runtime bridge script.
 * This gets written to a .js file inside the C3 project's scripts/ folder.
 */
export function generateBridgeScript(): string {
  return `// C3 Runtime Bridge — auto-generated by construct3-mcp
// Exposes the C3 runtime for external automation and testing.
// Do NOT edit manually; regenerate with inject_runtime_bridge tool.

runOnStartup(async (runtime) => {
  // Store runtime globally for external access
  globalThis.__c3Runtime = runtime;

  // Command/response bridge for structured communication
  const bridge = {
    // Pending commands from external tools
    _queue: [],
    // Results keyed by command ID
    _results: {},
    // Auto-incrementing command ID
    _nextId: 1,

    // Event subscriptions: bounded FIFO buffers filled from documented
    // runtime state each tick, and from explicit custom events.
    _subs: new Map(),
    _nextSub: 1,

    subscribe(eventType, filter, bufferSize) {
      filter = filter || {};
      var size = bufferSize === undefined ? 100 : bufferSize;
      if (!Number.isInteger(size) || size < 1 || size > 1000) throw new Error("bufferSize must be an integer from 1 to 1000");
      var sub = { id: "sub-" + this._nextSub++, type: eventType, filter: filter, size: size, buffer: [], baseline: undefined };
      if (eventType === "globalVarChange") {
        if (typeof filter.variable !== "string" || !filter.variable) throw new Error("globalVarChange needs filter.variable");
        if (!(filter.variable in runtime.globalVars)) throw new Error("Unknown global variable: " + filter.variable);
        sub.baseline = runtime.globalVars[filter.variable];
      } else if (eventType === "layoutChange") {
        sub.baseline = runtime.layout ? runtime.layout.name : null;
      } else if (eventType === "custom") {
        if (filter.name !== undefined && typeof filter.name !== "string") throw new Error("custom filter.name must be a string");
      } else {
        throw new Error("Unknown event type: " + eventType);
      }
      this._subs.set(sub.id, sub);
      return sub.id;
    },

    // Drop the oldest event before appending when the buffer is full.
    _push(sub, event) {
      if (sub.buffer.length >= sub.size) sub.buffer.shift();
      sub.buffer.push(event);
    },

    readEvents(id, clear) {
      var sub = this._subs.get(id);
      if (!sub) throw new Error("Unknown subscription: " + id);
      var events = sub.buffer.slice();
      if (clear === undefined || clear) sub.buffer.length = 0;
      return events;
    },

    unsubscribe(id) {
      return this._subs.delete(id);
    },

    // A custom event from the game's own script, or from a page evaluation.
    emit(name, data) {
      var delivered = 0;
      for (var sub of this._subs.values()) {
        if (sub.type !== "custom") continue;
        if (sub.filter.name !== undefined && sub.filter.name !== name) continue;
        this._push(sub, { type: "custom", name: name, value: data, timestamp: Date.now(), tick: runtime.tickCount });
        delivered++;
      }
      return delivered;
    },

    // Compare each subscription's baseline with the runtime; emit only real changes.
    _poll() {
      for (var sub of this._subs.values()) {
        if (sub.type === "globalVarChange") {
          var value = runtime.globalVars[sub.filter.variable];
          if (!Object.is(value, sub.baseline)) {
            this._push(sub, { type: "globalVarChange", name: sub.filter.variable, value: value, previousValue: sub.baseline, timestamp: Date.now(), tick: runtime.tickCount });
            sub.baseline = value;
          }
        } else if (sub.type === "layoutChange") {
          var layoutName = runtime.layout ? runtime.layout.name : null;
          if (!Object.is(layoutName, sub.baseline)) {
            this._push(sub, { type: "layoutChange", name: layoutName, value: layoutName, previousValue: sub.baseline, timestamp: Date.now(), tick: runtime.tickCount });
            sub.baseline = layoutName;
          }
        }
      }
    },

    // External tools call this to submit a command
    submit(type, args) {
      const id = this._nextId++;
      this._queue.push({ id, type, args });
      return id;
    },

    // External tools poll this to get results
    getResult(id) {
      const r = this._results[id];
      if (r) delete this._results[id]; // consume once
      return r ?? null;
    },

    // Current runtime state snapshot
    getState() {
      return {
        ready: true,
        layoutName: runtime.layout?.name ?? null,
        tickCount: runtime.tickCount,
        gameTime: runtime.gameTime,
        dt: runtime.dt,
        objectCount: runtime.objects ? Object.keys(runtime.objects).length : 0,
      };
    },
  };

  globalThis.__c3bridge = bridge;

  // Process command queue each tick
  runtime.addEventListener("tick", () => {
    while (bridge._queue.length > 0) {
      const cmd = bridge._queue.shift();
      try {
        let result;
        switch (cmd.type) {
          case "callFunction":
            result = runtime.callFunction(cmd.args.name, ...( cmd.args.params ?? []));
            break;

          case "getGlobalVar":
            result = runtime.globalVars[cmd.args.name];
            break;

          case "setGlobalVar":
            runtime.globalVars[cmd.args.name] = cmd.args.value;
            result = { set: true, name: cmd.args.name, value: cmd.args.value };
            break;

          case "getObjectState": {
            const objType = runtime.objects[cmd.args.objectName];
            if (!objType) {
              result = { error: "Object not found: " + cmd.args.objectName };
              break;
            }
            const inst = objType.getFirstInstance();
            if (!inst) {
              result = { error: "No instances of: " + cmd.args.objectName };
              break;
            }
            // Read requested properties or return defaults
            const props = cmd.args.properties ?? ["x", "y", "width", "height", "isVisible", "opacity"];
            const state = {};
            for (const p of props) {
              try { state[p] = inst[p]; } catch { state[p] = undefined; }
            }
            // Include instance variables
            if (inst.instVars) {
              state._instVars = {};
              for (const [k, v] of Object.entries(inst.instVars)) {
                state._instVars[k] = v;
              }
            }
            // Include behaviors
            if (inst.behaviors) {
              state._behaviors = {};
              for (const [k, v] of Object.entries(inst.behaviors)) {
                try { state._behaviors[k] = { exists: true }; } catch { /* skip */ }
              }
            }
            result = state;
            break;
          }

          case "getAllInstances": {
            const ot = runtime.objects[cmd.args.objectName];
            if (!ot) {
              result = { error: "Object not found: " + cmd.args.objectName };
              break;
            }
            const insts = ot.getAllInstances();
            result = {
              count: insts.length,
              instances: insts.slice(0, cmd.args.limit ?? 50).map((inst, i) => ({
                index: i,
                uid: inst.uid,
                x: inst.x, y: inst.y,
                isVisible: inst.isVisible,
              })),
            };
            break;
          }

          case "getLayout":
            result = {
              name: runtime.layout.name,
              width: runtime.layout.width,
              height: runtime.layout.height,
              layers: runtime.layout.getAllLayers().map(l => ({
                name: l.name,
                isVisible: l.isVisible,
                opacity: l.opacity,
                index: l.index,
              })),
            };
            break;

          case "goToLayout":
            runtime.goToLayout(cmd.args.name);
            result = { navigated: cmd.args.name };
            break;

          case "evaluateExpression": {
            // Evaluate a plugin expression by accessing an object's properties
            const obj = runtime.objects[cmd.args.objectName];
            if (!obj) {
              result = { error: "Object not found: " + cmd.args.objectName };
              break;
            }
            const instance = obj.getFirstInstance();
            if (!instance) {
              result = { error: "No instances of: " + cmd.args.objectName };
              break;
            }
            try {
              result = instance[cmd.args.expression];
            } catch (e) {
              result = { error: String(e) };
            }
            break;
          }

          case "layerToCssPx": {
            // Layout coordinates on a layer to CSS pixels relative to the
            // page viewport (client coordinates), through Construct's own
            // transform, so callers need not model scaling or letterboxing.
            const layer = runtime.layout.getLayer(cmd.args.layer ?? 0);
            if (!layer) {
              result = { error: "Layer not found: " + cmd.args.layer };
              break;
            }
            const [cssX, cssY] = layer.layerToCssPx(cmd.args.x, cmd.args.y);
            result = { x: cssX, y: cssY, layer: layer.name };
            break;
          }

          case "cssPxToLayer": {
            const layer = runtime.layout.getLayer(cmd.args.layer ?? 0);
            if (!layer) {
              result = { error: "Layer not found: " + cmd.args.layer };
              break;
            }
            const [layerX, layerY] = layer.cssPxToLayer(cmd.args.x, cmd.args.y);
            result = { x: layerX, y: layerY, layer: layer.name };
            break;
          }

          case "listObjects":
            result = Object.keys(runtime.objects);
            break;

          case "listGlobalVars":
            result = Object.entries(runtime.globalVars).reduce((acc, [k, v]) => {
              acc[k] = v;
              return acc;
            }, {});
            break;

          case "subscribeEvents":
            result = { subscription_id: bridge.subscribe(cmd.args.eventType, cmd.args.filter, cmd.args.bufferSize) };
            break;

          case "readEvents": {
            const events = bridge.readEvents(cmd.args.subscriptionId, cmd.args.clear);
            result = { events: events, count: events.length };
            break;
          }

          case "unsubscribeEvents": {
            if (!bridge.unsubscribe(cmd.args.subscriptionId)) {
              result = { error: "Unknown subscription: " + cmd.args.subscriptionId };
              break;
            }
            result = { subscription_id: cmd.args.subscriptionId, unsubscribed: true };
            break;
          }

          case "ping":
            result = { pong: true, time: Date.now() };
            break;

          default:
            result = { error: "Unknown command: " + cmd.type };
        }
        bridge._results[cmd.id] = { ok: true, value: result };
      } catch (e) {
        bridge._results[cmd.id] = { ok: false, error: String(e) };
      }
    }
    // Commands first, so a subscription made this tick records its baseline
    // and starts observing on the next one instead of reporting a false change.
    bridge._poll();
  });

  console.log("[c3-bridge] Runtime bridge initialized. Access via globalThis.__c3bridge");
});
`;
}

/**
 * Returns the path where the bridge script should be written
 * relative to the C3 project root.
 */
export function getBridgeScriptPath(): string {
  return 'scripts/c3-runtime-bridge.js';
}

/**
 * Returns the entry that needs to be added to the project's
 * script files list in project.c3proj.
 */
export function getBridgeProjectEntry(): { name: string; type: string; purpose: string } {
  return {
    name: 'c3-runtime-bridge.js',
    type: 'script',
    purpose: 'none', // auto-runs via runOnStartup
  };
}
